"""empty message

Revision ID: 8a62614302f5
Revises: c6d765c79324
Create Date: 2021-03-06 21:57:44.202552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a62614302f5'
down_revision = 'c6d765c79324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('char_class', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'char_class')
    # ### end Alembic commands ###
