"""empty message

Revision ID: c0e5963366be
Revises: 
Create Date: 2021-03-02 22:43:48.233361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e5963366be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('entries', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_entries_timestamp'), 'entries', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'entries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_index(op.f('ix_entries_timestamp'), table_name='entries')
    op.drop_column('entries', 'user_id')
    op.drop_column('entries', 'timestamp')
    # ### end Alembic commands ###
